### ISSUE TITLE
SupportedDevices array is incomplete on many macOS releases

### ISSUE THREAD

**Issue by erikng** [macadmins/sofa#101]
this caused an issue with https://github.com/macadmins/nudge/issues/600

I'm not sure what our solution should be here, other than assume than Apple never _drops_ supports for mac hardware midstream on major and try and backport. Ex: 14.5 supported devices can be back ported all the way to 14.0

At worst, some macs will be erronosuly marked as "supported" (ex: forked build, new mac device released) in older releases, but this is better than the current empty array.

https://github.com/macadmins/sofa/blob/main/v1/macos_data_feed.json#L246 see this for an example of the issue.

**Comment by erikng** [comment]
Also what happened, is Nudge informed devices incorrectly that they were no longer supported and needed to be replaced. 

I've worked around this issue by bailing on this logic if sofa returns an empty array, but I need this key to be configured properly, even if we do a manual one time thing as a source of truth, so we can properly show devices across people's fleet that they are in fact not supported.

**Comment by headmin** [comment]
This is because the GDMF data does not provide us with the desired `"SupportedDevices" []`  data for older OS version. We need to discuss in the SOFA team how we can best solve this problem.

**Comment by erikng** [comment]
I've addressed this, though for some reason the CI/CD job didn't update the json. Will look into it.
