### ISSUE TITLE
Ensure macOS 12 and higher are always in sofa feed, regardless of support status

### ISSUE THREAD

**Issue by erikng** [macadmins/sofa#102]
This might result in disagreements, but I just thought about this while fixing macOS 15 and https://github.com/macadmins/nudge/issues/603

If an admin is using `latest-minor` and does not care about security, if we pull macOS 12 when macOS 15 comes out, Nudge will stop Nudging. 

Ideally, a company should patch, but if they are attempting to get on the last version of macOS 12 while they figure out how to get to macOS 13+, nudge will no longer effectively ensure the company is at least running the last "secure" version.

**Comment by headmin** [comment]
With the new UI we can easily keep macOS 12

**Comment by erikng** [comment]
What about the json though?

**Comment by headmin** [comment]
Closing this issue as we keep macOS 12 in place already.
