### ISSUE TITLE
MacBook10,1 is not compatible with macOS Sonoma

### ISSUE THREAD

**Issue by ahousseini** [macadmins/sofa#183]
The model `MacBook10,1` is listed in the supported Macs for macOS Sonoma which is wrong. The latest compatible macOS version according to Mactracker is macOS Ventura. Unfortunately Apple does not list the latest compatible macOS version in this article: https://support.apple.com/en-ca/103257

**Comment by arubdesu** [comment]
Thanks for recording the issue, how would you recommend we resolve that?

**Comment by arubdesu** [comment]
(Whoops, totally overlooked that's our data 😅)
