### ISSUE TITLE
15.1 Update not available for some devices

### ISSUE THREAD

**Issue by jshirle2** [macadmins/sofa#201]
Hello!

Not sure if this is accurate, but based on the feed found here: https://sofafeed.macadmins.io/v1/macos_data_feed.json some models appear to be missing for eligible devices. Specifically, I noticed that my tester iMac which is model MGPJ3LL/A is not displayed there so is only receiving Nudge prompts to 15.0.1. 

Let me know if you need any further information. 

Thanks for a great tool!

**Comment by MagerValp** [comment]
gdmf's `PublicAssetSets:macOS` has two entries for 15.1, the forked M4 build `24B2083` and the regular `24B83`:
<img width="416" alt="image" src="https://github.com/user-attachments/assets/9b0aed54-2030-4399-8a76-85d94acfa4bf">

SOFA only picks up the forked M4 build and presents that as 15.1, with its rather limited list of supported devices.

**Comment by headmin** [comment]
The logic for forked builds must be improved, 4th the moment this issue is currently only addressed with a hot-fix #204 .

![image](https://github.com/user-attachments/assets/393ff556-0f90-4b56-9c23-1f0a54d3997f)
