### ISSUE TITLE
Feature request: RSS/Atom feed

### ISSUE THREAD

**Issue by smaddock** [macadmins/sofa#61]
This amazing aggregator would be easier to incorporate into our existing internal workflows if an RSS or Atom feed was generated, either in addition to the JSON feed or as a feature flag output style option when self hosting.

Possible solution: https://github.com/lkiesow/python-feedgen

**Comment by arubdesu** [comment]
Yup, this has been discussed and could be considered forthcoming!

**Comment by arubdesu** [comment]
(Disclaimer: I have no ETA. I want there to be wayyy more docs, even for how our GitHub Actions are working, and there's a lot of fun data we could add, but we'll try to carve out time for it all)

**Comment by headmin** [comment]
PR #72 merged.
Big thanks to @Johnnysramos for this feature and for adding requested changes.
