### ISSUE TITLE
Add Public Beta Info

### ISSUE THREAD

**Issue by Oh4sh0** [macadmins/sofa#62]
In conjunction with the RSS feed request, it would be awesome to also have detail about public beta releases. 

We have teams on the public beta to assist with testing, and because [Apple's Developer feed](https://developer.apple.com/news/releases/rss/releases.rss) only details private beta releases, it's difficult to give them automated notices about public betas becoming available to begin testing.

**Comment by arubdesu** [comment]
This might have to wait for some refactoring as we're hardcoding the one current stable Sonoma feed, but it's doable and a good idea, watch this space!

**Comment by arubdesu** [comment]
As I have a touch more info and we hope to be clearer about what we can provide or would like to put behind a 'flag'/self-hosted option, showing e.g. download links for stuff like ipsw's could get very tricky. As the discussion evolves and we can spend time on figuring out how to provide options we'll try to update this ticket, or at least chime in when something minimal can be agreed upon/close enough to going from design to some form of implementation.

**Comment by headmin** [comment]
The public beta for Sonoma is in the new UI, but we don't have fully automated scraping beta information yet. I'm closing this issue.
