### ISSUE TITLE
Pages are failing to load properly

### ISSUE THREAD

**Issue by WardsParadox** [macadmins/sofa#90]
![image](https://github.com/macadmins/sofa/assets/8117192/2809c36a-f153-444e-a931-f034559dc15a)

Looking in DOM, looks like something's breaking for some of the OS's

![image](https://github.com/macadmins/sofa/assets/8117192/59823338-fdaa-46fe-9a26-05752fc63618)

![image](https://github.com/macadmins/sofa/assets/8117192/a44bd362-cc74-4945-ba5f-13e5534f70fe)

**Comment by headmin** [comment]
Hi @WardsParadox thank you for the report. 
We do have a dependency on https://gdmf.apple.com/v2/pmv, and like others, we have observed numerous 403 errors when accessing the Apple service feed. We see `Request failed: 403 Client Error: Forbidden for url: https://gdmf.apple.com/v2/pmv`

This issue causes certain sections in our JSON feed to be blank, which subsequently affects the rendering of HTML from the JSON feed.

It seems that we need to cache the gdmf data, so the 403s does not affect us frequently when building the sofa feed file.

**Comment by headmin** [comment]
Added local caching for gdmf so we failover to cached version if we see a 403.
